services:
  nginx:
    image: nginx:alpine
    container_name: frontend_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./build:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf.template:/etc/nginx/templates/default.conf.template:ro
      - certbot_conf:/etc/letsencrypt:ro
      - certbot_www:/var/www/certbot:ro
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}

  certbot:
    image: certbot/certbot
    container_name: frontend_certbot
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --quiet; sleep 12h & wait $${!}; done;'"

volumes:
  certbot_conf:
  certbot_www:
